package.json
src/components/AppRoute.jsx
src/components/Photo.jsx
src/components/Viewer.jsx
src/constants/config.js
src/containers/Timeline.jsx
src/containers/ViewerToolbar.jsx
src/locales/en.json
src/styles/photo.styl
src/styles/viewer.styl
src/styles/viewerToolbar.styl
test/components/__snapshots__/photo.spec.jsx.snap
test/components/__snapshots__/photosList.spec.jsx.snap
test/components/__snapshots__/viewer.spec.jsx.snap
test/components/appRoute.spec.jsx
test/components/viewer.spec.jsx
test/containers/__snapshots__/timeline.spec.jsx.snap
test/containers/__snapshots__/toolbar.spec.jsx.snap
test/containers/__snapshots__/viewerToolbar.spec.jsx.snap
test/containers/timeline.spec.jsx
test/containers/toolbar.spec.jsx
test/containers/viewerToolbar.spec.jsx
yarn.lock

Add photo viewer

---

src/styles/app.styl

Double border between the cozy-bar and the app's body
Removed the extra border from the app's body

remove extra border

---

src/containers/Viewer.jsx
test/containers/__snapshots__/viewer.spec.jsx.snap
test/containers/viewer.spec.jsx

This PR improve the viewer component using a better code structure and tests.

Better viewer component + test

---

src/components/AppRoute.jsx
src/components/Nav.jsx
test/components/__snapshots__/nav.spec.jsx.snap
test/components/appRoute.spec.jsx

I removed the trash from the nav since it's not implemented at the moment.

[fix] Removed trash link

---

src/containers/Toolbar.jsx
src/reducers/ui.js
src/styles/albumsList.styl
src/styles/app.styl
src/styles/toolbar.styl
src/styles/topbar.styl
test/reducers/ui.spec.js

* Responsive albums list.
* Make top bar responsive for mobile views.
* Minor fix: Hide selection bar when album created with success

Topbar mobile + minor fix

---

package.json
src/actions/albums.js
src/actions/photos.js
src/components/Photo.jsx
src/components/PhotoList.jsx
test/components/__snapshots__/photo.spec.jsx.snap
test/components/__snapshots__/photoList.spec.jsx.snap
test/components/photo.spec.jsx
test/components/photoList.spec.jsx
test/containers/__snapshots__/addToAlbumModal.spec.jsx.snap
test/containers/__snapshots__/photoBoard.spec.jsx.snap
test/containers/addToAlbumModal.spec.jsx
test/containers/albumPhotos.spec.jsx
yarn.lock

This PR :
* Adds react-dimensions, we need it to be able to get photo list container width, and then give it to justified layou
* Adds (Justfied Layout by Flickr)[https://flickr.github.io/justified-layout/]
* Change photo structure to always get at least the parent container rendered. Give it a with and a height

[feat] Add justified layout for photo list ✨

---

package.json
yarn.lock

See https://github.com/cozy/cozy-files-v3/pull/141 since it's essentially the same problem.

[fix] Swiping to move between photos on firefox

---

src/components/AlbumItem.jsx
src/components/AlbumsList.jsx
src/components/Empty.jsx
src/components/ErrorComponent.jsx
src/containers/AddToAlbumModal.jsx
src/containers/AlbumsView.jsx
src/containers/PhotoBoard.jsx
test/components/__snapshots__/albumsList.spec.jsx.snap
test/components/albumsList.spec.jsx
test/containers/__snapshots__/addToAlbumModal.spec.jsx.snap

After these refactors, I'll add the *addToAnExistingAlbum* feature.

Can't stop refactoring

---

src/components/SelectAlbumItem.jsx
src/components/SelectAlbumsForm.jsx
src/containers/AddToAlbumModal.jsx
src/containers/AlbumsView.jsx
src/styles/addToAlbum.styl
src/styles/albumsList.styl
test/containers/__snapshots__/addToAlbumModal.spec.jsx.snap

In the popup, you can create a new album as previously
or select an existing album like the following screenshot

feat: add to existing album

---

src/containers/AddToAlbumModal.jsx
src/ducks/albums.js
src/locales/en.json

Two thinks in a row:
- use `Set` to remove duplicate when fetching albums' photo
- use `filter`/`indexOf` to remove already existing photos

fix: can add a photo only once :interrobang:

---

config/webpack.config.base.js
manifest.webapp
src/public/index.html

Configure the app to let `src/public/index.html` be accessible by everyone (not logged in) at `https://photos.cozy.tools:8080/public`.
Next step: beautify the page as asked here https://trello.com/c/gwhjazOi/279-1-pho-27-partage-d-un-album-par-lien-creation-d-une-page-publique-simple with a cozy-bar

feat: add a public folder :school:

---

src/containers/Toolbar.jsx
src/ducks/albums.js
src/locales/en.json

fix: display a message on success or error

---

config/webpack.config.dev.js
config/webpack.config.prod.js
package.json
src/index.ejs
src/main.jsx
yarn.lock

The same as https://github.com/cozy/cozy-drive/pull/254
+ I realized we did not add `preact/devtools` in photos, so I added it, free bonus! :tada:

chore: add piwik tracker + devtools

---

config/webpack.config.prod.js

There is two source file, output file have to be changed.

fix: build is not loading correct js file

---

src/styles/addToAlbum.styl

Updated for https://github.com/cozy/cozy-ui/pull/104

fix: adapt modal content

---

src/index.ejs
src/public/index.ejs

fix: discrimination for js file loading

---

config/webpack.config.dev.js
config/webpack.config.prod.js
src/main.jsx

Same as this one : https://github.com/cozy/cozy-drive/pull/265

feat: track user by id and app

---

package.json
src/components/ButtonClient.jsx
src/components/Sidebar.jsx
src/locales/en.json
src/styles/buttonclient.styl
src/styles/sidebar.styl
yarn.lock

Added the brand new button to invite users to download the Cozy desktop client.
Same as https://github.com/cozy/cozy-drive/pull/263 but applied to Photos (minor tweaks).

feat: Add button to client's download page

---

src/styles/albumsList.styl

Fixes the UI of the album list in the add-to-album modal.

fix: album list modal

---

src/components/SelectAlbumsForm.jsx
src/containers/AddToAlbumModal.jsx

Hides the list of album if it's empty when a photo is added to an album (only shows the album creation form).

feat: hide album list

---

package.json
src/containers/AddToAlbumModal.jsx
src/containers/ShareModal.jsx
src/styles/share.styl
yarn.lock

v3.0.0beta29 introduces some little changes for Modal. This PR should care that everything still works in Photos.

chore: update to Cozy UI v3.0.0beta29

---

src/index.ejs
src/lib/tracker.js
src/main.jsx
src/middlewares/EventTracker.js

Same as here : https://github.com/cozy/cozy-drive/pull/273

feat: enable event and conditional tracking

---

src/components/Viewer.jsx

The stuff that needs to be computed is now in the state instead of being computed at render time.

fix: re-enable keyboard navigation in viewer

---

src/styles/addToAlbum.styl
src/styles/albumsList.styl
src/styles/createAlbumForm.styl

Another round of fixes for this modal. Last one from me, I swear.

fix: Re: Re: Fwd: Re: add to album modal

---

.editorconfig
src/ducks/upload/UploadQueue.jsx
src/ducks/upload/styles.styl
src/locales/en.json

Hi @GoOz! I think I sort of stole this card from you, but I felt like a css challenge. #sorrynotsorry
It's mostly a big css reset since the natural behavior is close to what we're expecting on mobile.

feat: upload queue on mobile

---

src/containers/AlbumPhotos.jsx

Prevents the component to be rendered before the photos have been fetched.

fix: prevent album opening bug

---

src/ducks/albums/components/AlbumToolbar.jsx
src/public/App.jsx
src/public/index.styl
src/public/main.jsx

Fixes the title on the sharing page in mobile view, and the share link.

fix: title on mobile view

---

package.json
yarn.lock

chore: upgrade jest to v20

---

package.json
src/ducks/sharing/ShareModal.jsx
src/ducks/sharing/index.js
src/ducks/sharing/share.styl
src/locales/en.json
yarn.lock

Thanks to the new /sharings API, we are able to send a link to an existing cozy user.
Just enter his email address and his cozy's instance address and click on 'Send' button.
This feature is a cutting-edge technology and could be upgraded soon.
Made with :heart: by :goat::dash:

share an album to another cozy user

---

package.json
src/ducks/sharing/ShareModal.jsx
src/ducks/sharing/share.styl
src/locales/en.json
yarn.lock

The shareModal now respects the mockups, and texts are updated so it fits on 320px wide screens

fix: better sharemodal

---

src/ducks/sharing/ShareModal.jsx

fix: remove console.log

---

src/components/PhotoList.jsx
src/styles/newAlbum.styl
src/styles/photoList.styl

Few CSS changes and a change in "select all" button's position calculation.

fix: better layout for new album view

---

src/public/index.ejs

fix: locale on public page

---

src/components/AlbumItem.jsx
src/components/AlbumsList.jsx
src/containers/AlbumsView.jsx
src/ducks/sharing/index.js
src/styles/albumsList.styl

This is a relatively straightforward approach, but I wonder if it's the best.
I was thinking that it would be better to put all the sharing informations in the redux store (sharing type, permissions, etc), probably using `lists`. Opinions?

feat: Shared with me indicator

---

src/components/Viewer.jsx

Quick fix attempt for a bug I can't reproduce locally, and not very reliably on mobile either.

fix: prevent final update to mess things up

---

src/components/Recipient.jsx
src/containers/AlbumsView.jsx
src/ducks/sharing/ShareModal.jsx
src/ducks/sharing/index.js
src/locales/en.json
src/styles/recipient.styl

Add the view that displays the access list
@TODO get the access list from the API.

feat: Add 'who has access' to sharing modal

---

src/components/NewAlbum.jsx

Pictures worth explanation:
**before**
**after**

fix: a typo in i18n

---

src/ducks/sharing/ShareModal.jsx
src/ducks/sharing/WhoHasAccess.jsx
src/ducks/sharing/index.js
src/locales/en.json

Look at the `en.json` file and see how it's proper:
See https://github.com/cozy/cozy-stack/blob/master/docs/sharing.md#status for status label.

feat: proper the status of sharings

---

src/public/App.jsx
src/public/index.styl

Toolbar's menu now appears at <769px

fix: RWD for public toolbar

---

src/public/App.jsx
src/public/index.styl

Restored unshared error view that was stripped from @goldoraf refactoring and added some design  adaptation for mobile.

fix: restored unshared view + adaptation

---

src/ducks/sharing/components/ShareByEmail.jsx
src/ducks/sharing/index.js
src/ducks/sharing/share.styl
src/locales/en.json

Let user choose a sharing type:
_note: transparency is due to the screenshot, not real._

feat: choose sharing type

---

package.json

chore: include album sorting bugfix in release
