src/index.ejs
src/main.jsx

I spent a long time on having the whole thing not working, investigating into cozy-client-js, until I realized that the call to defineIndex was actually done too early, before the `DOMContentLoaded` event.

Handle app token and domain

---

src/actions/photos.js
src/components/Photo.jsx
test/components/__snapshots__/photosList.spec.jsx.snap
test/components/photo.spec.jsx

We should quicky think about a caching mechanism to store already fetch photo links (as they are constant)
Featuring a cozy-client-js polyfill experimentation. See https://github.com/cozy/cozy-client-js/pull/99

[feat] Retrieves download links with permission for photos in Photo component

---

src/actions/mango.js
src/actions/photos.js
test/actions/mango.spec.js

FYI: In the file `mango.js` the order of the items in `fields` array matters.
The fields you want to filter with must be on the left of the field you want to sort with.
Basically, first you filter then you sort.

feat: Hide trashed photos from Timeline

---

manifest.webapp
src/index.ejs
src/main.jsx

Adding Editor's name to the manifest so the stack can use it and make sure this data is shared so the cozy-bar can use it.
tl;dr: It displays the "Cozy" before the "Photos" in the Cozy-bar
Related PR: https://github.com/cozy/cozy-bar/pull/37

feat: Add Support for editor's name

---

src/actions/mango.js
test/actions/mango.spec.js

Files just uploaded appear on top of the timeline, for the moment, and then when you refresh or change the view they take their places by descending chronological order.
Pictures with no metadata datetime will be updated with one during the upload. The time added is the time of the upload of course.

feat: Sort photos by metadata datetime

---

src/components/DeleteButton.jsx
src/containers/Toolbar.jsx
src/ducks/albums.js
src/locales/en.json
test/containers/__snapshots__/toolbar.spec.jsx.snap

A big red button is displayed in album photos' view.
When it's clicked, the album is deleted and the user is redirected to the albums' view.
*Note: another PR will end this feature up.*

remove album [first work]

---

src/containers/SelectionBar.jsx
src/locales/en.json

fix: display a message on success or error

---

package.json
yarn.lock

We need the new cozy-bar version to remove unnecessary console.error.

fix: update cozy-bar version

---

config/webpack.config.copy-files.js
manifest.webapp

Regarding https://github.com/cozy/cozy-stack/pull/599#issuecomment-301519778 we moved the app icon to the `public/` folder

fix: move app icon to `public/`

---

package.json
src/ducks/albums/index.js
src/public/App.jsx
src/public/PhotosList.jsx
src/public/PublicAlbumView.jsx
src/public/main.js

It handles shared album by link with links like `http://photos.cozy.tools:8080/public?sharecode=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJzaGFyZSIsImlhdCI6MTQ5NTExOTIzOCwiaXNzIjoiY296eS50b29sczo4MDgwIiwic3ViIjoiZW1haWwifQ.Fo181yCEQoktjCVGr0pTdsU-W-GB_AizI1tGZm-X-lK6GYz2Bqts6yYwoEHDkVYJJgeFVy2UTqYkliYkb4pc6w&id=f6f96990b5af9be2b04ca9f832000c5f` where `sharecode` and `id` are respectively a cozy token with specific permissions and the shared album id.

feat: a very beautiful public page

---

src/ducks/upload/styles.styl
src/index.ejs
src/styles/addToAlbum.styl

Initial goal: the add-to-album modal now has a default width that matches the mockups.
Side quest: on chrome, in the responsive view, in *some* resolutions, the whole app was behaving very strangely. It was possible to scroll past the actual app both horizontally and vertically, to zoom out of the default view, and the selection bar was in the wrong place.
Turns out the hidden upload queue was causing all of this (although I think that might be a bug in chrome). Applying the translation only on the y axis solves this, and giving the queue a max width makes sure it doesn't go outside the frame on mobile.
Small fix, but it took me forever to find the issue!

fix: modal size and display issues

---

src/styles/addToAlbum.styl
src/styles/albumsList.styl
src/styles/createAlbumForm.styl

This PR fixes several problems with the add-to-album modal:
- The paddings, which probably conflicts with #97 and may need another update after the latest cozy-ui lands
- SIzing issues on mobile
- A thumbnail-rendering bug in chrome
- Missing borders

fix: Add to album modal css fixes

---

src/ducks/upload/styles.styl

I guess, in a way, in Chrome's mind, its behaviour made sense.
Anyway, this should fix the bug.

fix: scrolling bottom on Chrome mobile was funky

---

src/styles/photoList.styl

So `.pho-section` had a left margin which was kind of harmless at first, but when the AutoSizer plugin appeared, it forced the width of this element to the size of the viewport.
Which means viewport's size + margin = larger than the viewport and in that case there's something to scroll horizontally.
So I changed the margin with right & left padding and add a `box-sizing: border-box` so that even if width is calculated by AutoSizer, it renders accordingly. No more scroll. :)

fix: horizontal scrolling happened because of too large elements

---

src/ducks/upload/styles.styl

On some screen resolutions, the uploader didn't take the full with. Merging it right away, just doing the PR for the record (ping @GoOz)

fix: full width uploader on all resolutions

---

src/ducks/sharing/index.js

I don't know why, but it seems the collections name have changed for permission sets.
s/set.attributes.permissions.collection/set.attributes.permissions.albums/
---
Je ne sais pas pourquoi, mais on dirait que le nom des collections a changé pour les jeux de permission.
s/set.attributes.permissions.collection/set.attributes.permissions.albums/
@goldroraf an idea?

fix: update collection name

---

src/containers/AddToAlbumModal.jsx
src/ducks/timeline/index.js

The root cause is that after adding a photo to an album, it's references in the store become outdated. I've added a call that re-fetches the photos after they've been added so the store stays correct at all time.
The downside is that this needs to be done whenever an album changes, which currently only happens in `AddToAlbumModal`, but that's bound to change. @goldoraf since you're working on this, I'm curious to hear what you think.

fix: update timeline store after addition to album

---

src/ducks/sharing/index.js

It seems without this property, the sharing link is not working.
Do you confirm that @Gara64 ?
/poke @jsilvestre 
/fix #126

fix: share album needs this selector

---

src/components/Viewer.jsx

Here's a play by play of what was happening:
1. a pinch start is detected, the base values are computed
1. user does the pinching, everything is fine
1. user removes *one* finger from the pinch —— the pinch gesture ends here, everything is still correct
1. as the user removes the second finger a fraction of a second later, he/she moves a tiny bit
1. this produces a pan event —— but no pan start, because the finger was already there
1. the pan event is computed using the values set in step 1, which are now wrong
The fix makes sure the base values are re-calculated between steps 3 and 4.

fix: pan after pinch

---

src/styles/viewer.styl

In firefox, the photos are bigger than the page, at least on some screen sizes. Because of nested flexboxes, the the image tag was allowed to be bigger than it's parents. The proposed fix forces a max height again.

fix: firefox viewer overflow height

---

src/components/Viewer.jsx

Before: in the photo viewer, when changing photo, the old photo stayed and the loading indicator was next to it.
Now: the old photo disappears, there's only the loading indicator until the new photo is loaded

fix: photo loading indicator

---

manifest.webapp
src/ducks/sharing/index.js

This fixes an important bug that prevents users to share albums with others.

fix: permissions to share albums

---

src/containers/SelectionBarWithActions.jsx
src/ducks/selection/index.js
src/locales/en.json

Added an action in the selection bar enabling the download of photos.
For now, whether it's one or more photos, it generates a zip archive. 
It should be for 2 or more but since a refactoring is ongoing on Photos that would significantly make it easier to directly download one photo, I propose that we deal with it after that refactoring in another PR.

feat: add download photos action in selection bar

---

src/components/Viewer.jsx
src/components/ViewerToolbar.jsx
src/lib/redux-cozy-api.js
src/locales/en.json
src/styles/viewerToolbar.styl

Added a toolbar action in the Photo viewer so you can now download the photo currently displayed.
Don't know if it's the best way to do it but hey, that's what reviewers are for. 😄

feat: Add action in viewer toolbar to download photo

---

src/public/App.jsx
src/public/index.styl

Add menu item to download photo in public view when on mobile.

fix: add download album button on public page for mobile

---

src/containers/AlbumPhotos.jsx
src/containers/Timeline.jsx

When switching between the timeline and albums view, the selection is kept, because the state is never changed. This PR clears the selection when the user leaves the view.

fix: clear selection on view change

---

src/components/AlbumsList.jsx
src/components/SelectAlbumsForm.jsx
src/containers/AddToAlbumModal.jsx
src/containers/AlbumItem.jsx
src/containers/AlbumPhotos.jsx
src/containers/AlbumsView.jsx
src/containers/BoardView.jsx
src/containers/SelectionBarWithActions.jsx
src/ducks/albums/components/AlbumToolbar.jsx
src/ducks/sharing/index.js
src/ducks/sharing/withSharings.jsx
src/styles/albumsList.styl

Albums that are shared with me are read-only, so this PR updates the UI in several places to reflect that.
For the review, start with the `withSharings` HOC, as everything else depends on that. From now on, whenever we display an album, we need to know if it was shared, and how.  I think the correct way to do this would be through cozy-connect and the redux state, however I didn't know how to do that in a reasonable timeframe. 
Instead, I created a HOC that essentially does [this](https://github.com/cozy/cozy-photos-v3/blob/f2c3f7c587b5e4f0224f797084b0c93c932396e1/src/containers/AlbumsView.jsx#L35). It doesn't make the approach better, but at least it's consistent and all in one place, which should make things easier for the next refactoring bit.
All other changes are minor refactorings …

refactor: disable some actions for shared albums

---

src/ducks/sharing/share.styl

As you can see in the screenshot, I spotted two things:
1. The height is not the same as the button
1. We may have a tooling problem when generating CSS

fix: use cozy-ui style :nail_care:

---

src/ducks/sharing/components/ShareByLink.jsx
src/ducks/sharing/index.js

Everytime user opens the sharingModal, if the permission/sharing did not exist, it was created.

fix: sharing link was generated everytime :bug:

---

src/ducks/sharing/components/WhoHasAccess.jsx

A tiny hack to treat any `undefined` status as pending (waiting for the status to be defined).

fix: treat undefined as pending :bug:

---

src/ducks/sharing/share.styl

I guess @GoOz will have a better solution for such a problem. But I am not familiar with side-effects on changing something in [cozy-ui](https://github.com/cozy/cozy-ui).
Then, before:
and after:

fix: select and button the same size

---

src/ducks/sharing/components/ShareByEmail.jsx
src/lib/redux-cozy-client/CozyAPI.js

The response format when calling `cozy.client.files.query` and `cozy.client.data.query` is a bit different. For data, the format is documented [here](
https://github.com/cozy/cozy-stack/blob/master/docs/mango.md#find-documents), but for files, I couldn't find it.
Anyway, right now (AFAIK) we only use `cozy.client.files.query` so everything works fine, but if you try to query the data API (querying `io.cozy.photos.albums` for example) things will explode. So here's a preventive fix for that.

fix: query DATA API
